######################################################
# BPE Neural Network Parameter Config File           #
######################################################

######################################################
#                 Data Configurations                #
######################################################
pad_limit : 150

######################################################
#                  HyperParams                       #
######################################################
# Types [shallow, deep]
# Shallow: 1 Conv Layer
# Deep : 3 Conv Layers
model_type : shallow
embedding_dim : 300
# --- !hyperparams
epochs : 2

optimizer : adam
learning_rate : 0.0001 # 0.0001
beta1 : 0.9
beta2 : 0.999
epsilon: 10e-8

batch_size : 8

######################################################
#                 Train Parameters                   #
######################################################

dataset : subj
train_data_location : data/

keras_tokenizer_loc  : models/

if_softmax : false
num_classes : 6


# 30% Split of the data
# -------------------
# 70% for training
# 20% for testing
# 10% for validation
train_test_split_ratio : 0.2
validation_split_ratio : 0.0 # 0.2

early_stopping : true

using_cv : false
cross_validation_k : 10

save_location : checkpoints/

######################################################
#              Inference Parameters                  #
######################################################

model_loc : models/
use_file_input : yaml